//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DictionaryHistoryItem;

@protocol DictionaryHistoryDelegate <NSObject>
- (void)dictionaryHistoryDidEndLiveTransitionWithCancelled:(BOOL)arg1;
- (void)dictionaryHistoryWillStartLiveTransition;
- (BOOL)needStopTransitionBeforeUpdate;
- (void)dictionaryHistorySelectedIndexDidChanged;
- (void)displayDictionaryHistory:(DictionaryHistoryItem *)arg1;
@end

