//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@class NSString, NSURL;

@interface DictionaryBrowserApp : NSApplication
{
    NSURL *_pendedLaunchURL;
    NSString *_pendedLaunchString;
    NSString *_pendedDictionaryPath;
}

- (void)_handleURLEvent:(id)arg1 withReplyEvent:(id)arg2;
- (void)sendEvent:(id)arg1;
- (void)preprocessEvent:(id)arg1;
- (void)processPendedURLRequest;
- (void)handleURLRequest:(id)arg1;
- (void)processPendedStringRequest;
- (void)handleStringRequest:(id)arg1 inDictionaryPath:(id)arg2;
- (BOOL)hasPendedRequest;
- (void)finishLaunching;

@end

