//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@interface DSIndexTableCell : NSTextFieldCell
{
}

+ (id)_simplifiedChineseAttrWithBaseFont:(id)arg1 forPinyin:(BOOL)arg2;
- (id)_hilightedAttributedStringForBaseString:(id)arg1 useBold:(BOOL)arg2;
- (id)_myAttributedStringValueWithController:(id)arg1 forTopLabel:(BOOL)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

