//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface DSIndexTableView : NSTableView
{
    BOOL _showingSpellCorrectedWords;
}

@property BOOL showingSpellCorrectedWords; // @synthesize showingSpellCorrectedWords=_showingSpellCorrectedWords;

@end

