//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DictionaryObj;

@interface FakeRecordForResume : NSObject
{
    DictionaryObj *_dictionaryObj;
}

- (id)dictionary;
- (id)anchor;
- (void)dealloc;
- (id)initWithDictionaryIdentifier:(id)arg1;

@end

