//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (CocoaExtensions)
+ (id)stringWithFourCharCode:(unsigned int)arg1;
- (long long)normalizedKeyCompare:(id)arg1 range:(struct _NSRange)arg2;
- (long long)normalizedKeyCompare:(id)arg1;
- (id)normalizedKey;
- (unsigned long long)commonPrefixLength:(id)arg1;
- (id)attributedStringForTruncation:(unsigned long long)arg1;
- (unsigned int)fourCharCodeValue;
@end

