/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DSDictionaryObj.h"

@class NSString;

@interface WikipediaDictionaryObj : DSDictionaryObj
{
    NSString *_errorHTMLTemplate;
    NSString *_footerHTMLTemplate;
    NSString *_postProcessScriptTemplate;
    NSString *_disclaimerString;
    BOOL _errorOccurred;
}

+ (BOOL)handleThisDCSDictionaryRef:(struct __DCSDictionary *)arg1;
- (void)dealloc;
- (void)setInFocus:(BOOL)arg1;
- (void)_postNotificationWithDelay:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned long long)arg2 maxRecord:(long long)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
- (id)noEntriesFoundString;
- (id)postProcessScriptForFrame:(id)arg1 loadFinished:(char *)arg2;
- (id)labelName;
- (void)setLabelName:(id)arg1;
- (long long)foundCountCap;
- (id)errorHTMLTemplate;
- (id)footerHTMLTemplate;
- (id)postProcessScriptTemplate;
- (id)disclaimerString;

@end

