/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSScrollView.h"

@class WebView;

@interface WebWrapScrollView : NSScrollView
{
    WebView *_webview;
    struct CGRect _lastSmartZoomTargetRect;
}

- (struct CGRect)_selectionRect;
- (void)_adjustInnerWebView:(BOOL)arg1;
- (void)_scrollViewDidEndLiveMagnify:(id)arg1;
- (void)scrollToEndOfDocument:(id)arg1;
- (void)scrollToBeginningOfDocument:(id)arg1;
- (void)smartMagnifyWithEvent:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (BOOL)jumpToSelection;
- (void)scrollToOffset:(float)arg1 animate:(BOOL)arg2;
- (void)setScrollPositionToOffsetInPage:(float)arg1;
- (float)scrollPositionFromTopOfPage;
- (void)reflectWebViewChangeWithResetScroll:(BOOL)arg1;
- (BOOL)processKeyCommand:(SEL)arg1;
- (void)dealloc;
- (id)initAndReplaceWithWebView:(id)arg1;

@end

