/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Lookup/LUImagesModule.h>

@class NSMutableSet;

@interface LUBingImagesModule : LUImagesModule
{
    unsigned long long _duplicates;
    unsigned long long _queryOffset;
    NSMutableSet *_imageURLs;
}

@property(retain) NSMutableSet *imageURLs; // @synthesize imageURLs=_imageURLs;
@property unsigned long long queryOffset; // @synthesize queryOffset=_queryOffset;
@property unsigned long long duplicates; // @synthesize duplicates=_duplicates;
- (unsigned long long)maxSimultaneousDownloads;
- (unsigned long long)maxThumbnails;
- (id)thumbnailHeaders;
- (id)queryHeaders;
- (id)moreURL;
- (void)lookupSearchTerm;
- (void)setSearchTerm:(id)arg1 language:(id)arg2 partOfSpeech:(id)arg3;
- (id)providerName;
- (void)dealloc;
- (id)init;

@end

