/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface LUColorView : NSView
{
    NSColor *_color;
}

@property(retain) NSColor *color; // @synthesize color=_color;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

