/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSDefinitionExternalModule-Protocol.h"

@interface LULookupDefinitionModule : NSObject <NSDefinitionExternalModule>
{
}

+ (void)hideDefinition;
+ (void)showDefinitionForTerm:(id)arg1 atLocation:(struct CGPoint)arg2 options:(id)arg3;
+ (struct _NSRange)tokenRangeForString:(id)arg1 range:(struct _NSRange)arg2 options:(id *)arg3;
+ (void)focusTermUsingQueue:(struct dispatch_queue_s *)arg1 handler:(id)arg2;
- (void)showDefinitionByHotKey;
- (void)showDefinitionForString:(id)arg1 range:(struct _NSRange)arg2 options:(id)arg3 originProvider:(void *)arg4 inView:(id)arg5;

@end

