/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewController.h"

@class LUColorView, LUTitleLink, NSPopUpButton, NSTextField;

@interface LUModuleHeader : NSViewController
{
    LUTitleLink *_moduleTitle;
    NSTextField *_moduleSubtitle;
    NSPopUpButton *_modulePopup;
    LUColorView *_dividerLine;
    LUColorView *_dividerLineEngraving;
}

@property(retain) LUColorView *dividerLineEngraving; // @synthesize dividerLineEngraving=_dividerLineEngraving;
@property(retain) LUColorView *dividerLine; // @synthesize dividerLine=_dividerLine;
@property(retain) NSPopUpButton *modulePopup; // @synthesize modulePopup=_modulePopup;
@property(retain) NSTextField *moduleSubtitle; // @synthesize moduleSubtitle=_moduleSubtitle;
@property(retain) LUTitleLink *moduleTitle; // @synthesize moduleTitle=_moduleTitle;
- (void)openLinkURL:(id)arg1;
- (void)setTitle:(id)arg1 subtitle:(id)arg2 menu:(id)arg3;
- (void)dealloc;
- (id)init;

@end

