/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class LUModule, LUModuleHeader;

@interface LUModuleInfo : NSObject
{
    LUModule *_module;
    LUModuleHeader *_header;
    struct CGRect _moduleViewDesiredFrame;
    BOOL _moduleViewDesiredHidden;
    struct CGRect _headerViewDesiredFrame;
    BOOL _headerViewDesiredHidden;
}

@property BOOL headerViewDesiredHidden; // @synthesize headerViewDesiredHidden=_headerViewDesiredHidden;
@property struct CGRect headerViewDesiredFrame; // @synthesize headerViewDesiredFrame=_headerViewDesiredFrame;
@property BOOL moduleViewDesiredHidden; // @synthesize moduleViewDesiredHidden=_moduleViewDesiredHidden;
@property struct CGRect moduleViewDesiredFrame; // @synthesize moduleViewDesiredFrame=_moduleViewDesiredFrame;
@property(retain) LUModuleHeader *header; // @synthesize header=_header;
@property(retain) LUModule *module; // @synthesize module=_module;
- (void)dealloc;
- (id)initWithModule:(id)arg1 menu:(id)arg2;

@end

