/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewController.h"

@class NSProgressIndicator, NSView;

@interface LUNoResultsViewController : NSViewController
{
    NSView *_searchingView;
    NSView *_noResultsView;
    NSProgressIndicator *_progressIndicator;
}

@property(retain) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain) NSView *noResultsView; // @synthesize noResultsView=_noResultsView;
@property(retain) NSView *searchingView; // @synthesize searchingView=_searchingView;
- (void)dealloc;
- (id)init;

@end

