/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSPopover.h"

#import "NSPopoverDelegate-Protocol.h"

@class NSView;

@interface LUResultsPopover : NSPopover <NSPopoverDelegate>
{
    NSView *_targetView;
    struct CGRect _targetRect;
    BOOL _everBeenShown;
}

@property(getter=hasEverBeenShown) BOOL everBeenShown; // @synthesize everBeenShown=_everBeenShown;
@property struct CGRect targetRect; // @synthesize targetRect=_targetRect;
@property(retain) NSView *targetView; // @synthesize targetView=_targetView;
- (void)observeClipViewNotification:(id)arg1;
- (void)observeResultsViewNotification:(id)arg1;
- (void)setSearchTerm:(id)arg1 language:(id)arg2 partOfSpeech:(id)arg3 targetView:(id)arg4 targetRect:(struct CGRect)arg5;
- (void)cancelOperation:(id)arg1;
- (void)popoverWillClose:(id)arg1;
- (void)popoverDidShow:(id)arg1;
- (void)dealloc;
- (id)init;

@end

