/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSViewController.h"

@class LUColorView, LUTitleLink, NSButton, NSPopUpButton, NSTextField;

@interface LUResultsTitleViewController : NSViewController
{
    LUTitleLink *_titleText;
    NSButton *_backButton;
    NSTextField *_titleSubtitle;
    NSPopUpButton *_titlePopup;
    LUColorView *_leftLine;
    LUColorView *_leftLineEngraving;
    LUColorView *_rightLine;
    LUColorView *_rightLineEngraving;
}

@property(retain) LUColorView *rightLineEngraving; // @synthesize rightLineEngraving=_rightLineEngraving;
@property(retain) LUColorView *rightLine; // @synthesize rightLine=_rightLine;
@property(retain) LUColorView *leftLineEngraving; // @synthesize leftLineEngraving=_leftLineEngraving;
@property(retain) LUColorView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain) NSPopUpButton *titlePopup; // @synthesize titlePopup=_titlePopup;
@property(retain) NSTextField *titleSubtitle; // @synthesize titleSubtitle=_titleSubtitle;
@property(retain) NSButton *backButton; // @synthesize backButton=_backButton;
@property(retain) LUTitleLink *titleText; // @synthesize titleText=_titleText;
- (void)openLinkURL:(id)arg1;
- (void)goBack:(id)arg1;
- (void)setTitle:(id)arg1 subtitle:(id)arg2 menu:(id)arg3 backButton:(BOOL)arg4 linkURL:(id)arg5 linkDescription:(id)arg6;
- (void)dealloc;
- (id)init;

@end

