/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@interface LURolloverHighlight : NSView
{
    BOOL _mouseInside;
}

@property BOOL mouseInside; // @synthesize mouseInside=_mouseInside;
- (void)viewDidUnhide;
- (void)drawRect:(struct CGRect)arg1;
- (void)cursorUpdate:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)init;

@end

