/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButton.h"

@class NSDictionary, NSString, NSURL;

@interface LUTitleLink : NSButton
{
    NSURL *_linkURL;
    NSString *_linkDescription;
    NSDictionary *_standardAttributes;
    NSDictionary *_rolloverAttributes;
}

@property(retain) NSDictionary *rolloverAttributes; // @synthesize rolloverAttributes=_rolloverAttributes;
@property(retain) NSDictionary *standardAttributes; // @synthesize standardAttributes=_standardAttributes;
@property(retain) NSString *linkDescription; // @synthesize linkDescription=_linkDescription;
@property(retain) NSURL *linkURL; // @synthesize linkURL=_linkURL;
- (void)setAttributes:(id)arg1;
- (void)setLink:(id)arg1 description:(id)arg2;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)cursorUpdate:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

