/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface LUWebServicesPreferences : NSObject
{
    NSString *_cachedWebSearchProvider;
    NSString *_cachedImageSearchProvider;
}

+ (id)sharedPreferences;
@property(retain) NSString *cachedImageSearchProvider; // @synthesize cachedImageSearchProvider=_cachedImageSearchProvider;
@property(retain) NSString *cachedWebSearchProvider; // @synthesize cachedWebSearchProvider=_cachedWebSearchProvider;
@property(retain) NSString *imageSearchProvider;
@property(readonly) NSString *webSearchProvider;
- (void)updateCachedValues;
- (void)commonLUWebServicesPreferencesTeardown;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

