/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Lookup/LUImagesModule.h>

@interface LUYahooImagesModule : LUImagesModule
{
}

- (unsigned long long)maxSimultaneousDownloads;
- (unsigned long long)maxThumbnails;
- (id)thumbnailHeaders;
- (id)queryHeaders;
- (id)moreURL;
- (void)setSearchTerm:(id)arg1 language:(id)arg2 partOfSpeech:(id)arg3;
- (id)providerName;

@end

