/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol NSDefinitionExternalModule
- (void)showDefinitionByHotKey;
- (void)showDefinitionForString:(id)arg1 range:(struct _NSRange)arg2 options:(id)arg3 originProvider:(void *)arg4 inView:(id)arg5;
@end

