#! /bin/bash
#
# Close all instances of Dictionary.app
`killall Dictionary`

# Check for SIMBL directory
if [ ! -d $HOME/Library/Application\ Support/SIMBL/Plugins ] 
then
#	echo "It seems that SIMBL is not installed on this computer."
#	echo "You can download SIMBL from http://www.culater.net/software/SIMBL/SIMBL.php"
#	exit
	`mkdir -p $HOME/Library/Application\ Support/SIMBL/Plugins`
fi


# Remove the existing bundle from SIMBL plugins folder
`rm -rf $HOME/Library/Application\ Support/SIMBL/Plugins/BetterDictionary.bundle/`

# Copy the bundle to SIMBL plugins folder
`cp -R $0/../BetterDictionary.bundle/ $HOME/Library/Application\ Support/SIMBL/Plugins/BetterDictionary.bundle/`

# Run Dictionary.app
`open /Applications/Dictionary.app/`

exit 0