/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DictionaryFoundIndexItem : NSObject
{
    NSString *_searchKey;
    NSString *_title;
    NSString *_semiNormalizedTitle;
    unsigned int _flag;
}

- (id)initWithSearchKey:(id)arg1 title:(id)arg2 flag:(unsigned long)arg3;
- (void)dealloc;
- (id)searchKey;
- (id)title;
- (id)semiNormalizedTitle;
- (unsigned long)flag;
- (void)setFlag:(unsigned long)arg1;

@end

