/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface DictionaryFoundRecords : NSObject
{
    NSMutableDictionary *_titleDictionary;
    NSMutableDictionary *_recordDictionary;
    BOOL _needToSortTitleArray;
    BOOL _needToSortSearchKeyArray;
    unsigned int _lastFilterMask;
    NSArray *_sortedSearchKeyArray;
    NSArray *_sortedTitleArray;
    NSMutableDictionary *_properties;
    NSString *_searchString;
    NSString *_sortHintOriginal;
    NSString *_sortHintSemiNormalized;
    NSString *_sortHintNormalized;
    NSMutableArray *_tempOriginalDictionaryOrder;
    NSMutableDictionary *_headwordTitleMapping;
}

+ (id)foundRecordsWithSearchString:(id)arg1;
- (void)dealloc;
- (void)addRecord:(id)arg1;
- (void)addRecordsFromFoundRecords:(id)arg1;
- (unsigned int)count;
- (id)indexWordArray;
- (id)firstIndexWord;
- (id)searchKeyArray;
- (id)recordArrayForIndexWord:(id)arg1;
- (id)recordArrayForSearchKey:(id)arg1;
- (id)searchKeyForIndexWord:(id)arg1;
- (void)setProperty:(id)arg1 forKey:(id)arg2;
- (id)propertyForKey:(id)arg1;
- (void)setProperty:(id)arg1 forDictionary:(id)arg2 withKey:(id)arg3;
- (id)propertyForDictionary:(id)arg1 withKey:(id)arg2;
- (void)setFilterMask:(unsigned long)arg1;
- (id)_recordDictionary;
- (void)_setSearchString:(id)arg1;
- (id)_searchString;
- (void)_setSortingHint:(id)arg1;
- (id)_sortingHintOriginal;
- (id)_sortingHintSemiNormalized;
- (id)_sortingHintNormalized;
- (id)_tempOriginalDictionaryOrder;
- (id)_allFilteredItemsOfDictionary:(id)arg1;
- (id)_properties;
- (id)_sortRecordArray:(id)arg1 withSortHint:(id)arg2;
- (id)_indexItemForIndexWord:(id)arg1;

@end

