/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol DSDictionaryProtocol
+ (id)registeredDictionaries;
- (id)initWithPath:(id)arg1;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLString;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
@end

