/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DSDictionaryObj, NSFont, NSIndexSet, NSMutableArray, NSMutableDictionary, NSString, NSURL, NSWindow, WebView;

@interface PreferenceController : NSObject
{
    NSWindow *_preferenceWindow;
    NSMutableArray *_dictionariesWithFlags;
    NSFont *_copyrightFont;
    NSString *_defaultSizeString;
    NSIndexSet *_dictionaryListSet;
    id _pronunciationRadioButton;
    id _contextualMenuBehaviorRadioButton;
    WebView *_dictPrefWebView;
    int _pronunciationNortation;
    int _contextualMenuBehavior;
    BOOL _parentalControlEnabled;
    NSURL *_emptyPrefsHTMLURL;
    DSDictionaryObj *_lastSelectedDictionary;
    int _numberOfDictionaries;
    BOOL _loadingHTML;
    BOOL _windowWillCloseDone;
    NSMutableDictionary *_childNameArchive;
}

+ (id)sharedPreferenceWithCreate:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (void)show;
- (void)prepareToQuit;
- (id)dictionaryInfoArray;
- (void)windowWillClose:(id)arg1;
- (void)setDefaultSizeString:(id)arg1;
- (struct ComponentRecord *)_findDictionaryServiceComponent;
- (void)pronunciationChoosed:(id)arg1;
- (void)contextualMenuBehaviorChoosed:(id)arg1;
- (void)setDictionariesWithFlags:(id)arg1;
- (void)setDictionaryListSet:(id)arg1;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2;
- (void)_updateCurrentDictionaryPrefs;
- (id)_retrievePrefsFromHTML;
- (void)_setPrefsToHTML:(id)arg1 withCopyright:(id)arg2;
- (id)_copyrightHTML:(id)arg1 withFontSize:(id)arg2;
- (long)pronunciationNortation;
- (long)contextualMenuBehavior;

@end

