/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SlidingView : NSObject
{
    struct _NSPoint _startingLocation;
    struct _NSPoint _destination;
    double _startTime;
    double _duration;
}

- (id)initWithLocation:(struct _NSPoint)arg1 destination:(struct _NSPoint)arg2 travelTime:(double)arg3;
- (struct _NSPoint)destination;
- (struct _NSPoint)position;

@end

