/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DSDictionaryObj.h"

@class NSLocale, NSLock, NSMutableArray, NSString, NSTimer;

@interface WikipediaLanguageHandler : DSDictionaryObj
{
    NSString *_languageCode;
    NSString *_languageIDForWikiDomain;
    NSString *_languageIDForWikiVariant;
    NSString *_languageIDForPrefs;
    NSString *_languageName;
    NSLocale *_locale;
    id _parent;
    NSString *_indexQueryURL;
    NSString *_indexQueryString;
    int _maxIndexes;
    int _indexQueryTimeout;
    NSMutableArray *_runningConnections;
    NSLock *_connectionLock;
    int _pingInterval;
    int _pingTimeout;
    BOOL _serverAvailable;
    NSLock *_serverAvailableLock;
    NSTimer *_serverCheckTimer;
}

- (id)initWithParent:(id)arg1 forLanguage:(id)arg2;
- (void)dealloc;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)dictionaryPathForPrefs;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
- (BOOL)isLocalDictionary;
- (id)noEntriesFoundString;
- (BOOL)serverAvailable;
- (void)setServerAvailable:(BOOL)arg1;
- (id)children;
- (id)parent;
- (id)languageCode;
- (id)languageIDForWikiDomain;
- (id)languageName;
- (id)locale;
- (void)setInUse:(BOOL)arg1;
- (void)setInFocus:(BOOL)arg1;
- (id)postProcessScriptForFrame:(id)arg1 loadFinished:(char *)arg2;
- (id)labelName;
- (id)_indexQueryURL;
- (id)_actualLanguageCode:(BOOL)arg1;
- (id)_appendLanguageNameIfNeeded:(id)arg1 shortForm:(BOOL)arg2;
- (void)_cancelPreviousConnections;
- (void)_addConnectionToList:(id)arg1;
- (void)_removeConnectionFromList:(id)arg1;
- (id)_escapedStringForWikipediaURL:(id)arg1;
- (id)_unescapedStringForWikipediaURL:(id)arg1;

@end

