/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DictionaryRecord.h"

@interface WikipediaDictionaryRecord : DictionaryRecord
{
    BOOL _escapedKey;
    BOOL _censored;
    BOOL _blockedByCensoring;
}

- (id)initWithKey:(id)arg1 dictionary:(id)arg2 headword:(id)arg3 uniqueID:(unsigned long long)arg4 escapedKey:(BOOL)arg5;
- (BOOL)escapedKey;
- (void)setCensored:(BOOL)arg1;
- (BOOL)censored;
- (void)setBlockedByCensoring:(BOOL)arg1;
- (BOOL)blockedByCensoring;
- (id)normalizeTitle:(id)arg1;

@end

