//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 14 2013 08:30:39).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSPageControllerDelegate.h"

@class NSPageController;

@interface DictionaryHistory : NSObject <NSPageControllerDelegate>
{
    NSPageController *_pageController;
    id <DictionaryHistoryDelegate> _delegate;
    BOOL _settingForwardObject;
    BOOL _needToHideHistoryTransition;
    BOOL _delayHideHistoryTransition;
    BOOL _needToUpdateDiaplayEndTransition;
}

@property(nonatomic) id <DictionaryHistoryDelegate> delegate; // @synthesize delegate=_delegate;
- (void)pageControllerDidEndLiveTransition:(id)arg1;
- (void)pageController:(id)arg1 didTransitionToObject:(id)arg2;
- (void)pageControllerWillStartLiveTransition:(id)arg1;
- (void)_debugPrintHistoryInfo;
- (void)_checkNextItemIsNull;
- (void)completeTransition;
- (void)setSelectedHistoryIndex:(long long)arg1 withAnimation:(BOOL)arg2;
- (long long)selectedHistoryIndex;
- (id)historyItemsArray;
- (void)setCurrentHistoryToNUll;
- (void)clearAllHistoryItems;
- (void)setForwardHistoryItem:(id)arg1;
- (void)setCurrentHistoryItem:(id)arg1;
- (id)currentHistoryItem;
- (void)dealloc;
- (id)initWithPageContoller:(id)arg1;
- (id)initWithPageView:(id)arg1;

@end

