//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 14 2013 08:30:39).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSMenu;

@interface DictionaryScopeBarButton : NSButton
{
    NSMenu *_contextMenu;
    id _representedObject;
}

@property(retain) id representedObject; // @synthesize representedObject=_representedObject;
@property(retain) NSMenu *contextMenu; // @synthesize contextMenu=_contextMenu;
- (id)menuForEvent:(id)arg1;
- (void)dealloc;

@end

