//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 14 2013 08:30:39).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface DSIndexTableView : NSTableView
{
    BOOL _showingSpellCorrectedWords;
}

@property BOOL showingSpellCorrectedWords; // @synthesize showingSpellCorrectedWords=_showingSpellCorrectedWords;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
- (void)drawBackgroundInClipRect:(struct CGRect)arg1;

@end

