//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 14 2013 08:30:39).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSplitView.h"

@interface DSIndexSplitView : NSSplitView
{
}

- (id)accessibilityAttributeValue:(id)arg1;
- (id)dividerColor;

@end

