//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 14 2013 08:30:39).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebDocumentText.h"

@class NSArray, NSImage, NSPasteboard, NSView;

@protocol WebDocumentSelection <WebDocumentText>
- (NSView *)selectionView;
- (struct CGRect)selectionImageRect;
- (NSImage *)selectionImageForcingBlackText:(BOOL)arg1;
- (struct CGRect)selectionRect;
- (NSArray *)selectionTextRects;
- (void)writeSelectionWithPasteboardTypes:(NSArray *)arg1 toPasteboard:(NSPasteboard *)arg2;
- (NSArray *)pasteboardTypesForSelection;
@end

