/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DictionarySearchOperation, NSString;

@interface DictionaryObj : NSObject
{
    struct __DCSDictionary *_dictionaryRef;
    NSString *_customLabelName;
    DictionarySearchOperation *_lastRequest;
    BOOL _focused;
}

+ (void)registerSubClassName:(id)arg1;
+ (BOOL)handleThisDCSDictionaryRef:(struct __DCSDictionary *)arg1;
+ (id)availableDictionaries;
+ (id)activeDictionaries;
+ (id)dictionaryWithDCSDictionaryRef:(struct __DCSDictionary *)arg1;
+ (id)dictionaryWithIdentifier:(id)arg1;
+ (id)dictionaryWithPath:(id)arg1;
+ (long long)defaultFoundCountCap;
- (id)_initWithDCSDictionaryRef:(struct __DCSDictionary *)arg1;
- (void)dealloc;
- (id)dictionaryPath;
- (id)dictionaryName;
- (id)identifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)copyright;
- (id)contentsBaseURL;
- (id)cssFileURL;
- (BOOL)isLocalDictionary;
- (id)infoDictionary;
- (struct __DCSDictionary *)dictionaryRef;
- (id)parent;
- (id)children;
- (id)labelName;
- (void)setLabelName:(id)arg1;
- (id)customLabelName;
- (id)prefsHTMLString;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)appSpecificSettingForKey:(id)arg1;
- (void)setAppSpecificSetting:(id)arg1 forKey:(id)arg2;
- (long long)foundCountCap;
- (id)searchString:(id)arg1 byMethod:(long long)arg2 maxRecord:(long long)arg3;
- (id)searchReferenceID:(id)arg1;
- (void)asyncSearchString:(id)arg1 byMethod:(long long)arg2 maxRecord:(long long)arg3 allowGuess:(BOOL)arg4 queue:(id)arg5 transactionID:(long long)arg6 userInfo:(void *)arg7;
- (void)asyncCheckGuessedWords:(id)arg1 forSearchString:(id)arg2 queue:(id)arg3 transactionID:(long long)arg4 userInfo:(void *)arg5;
- (id)postProcessScriptForFrame:(id)arg1 records:(id)arg2 loadFinished:(char *)arg3;
- (id)accessErrorString;
- (void)preparingLoadingRecord:(id)arg1;
- (id)specialContentsForRecord:(id)arg1;
- (void)_setDCSDictionaryRef:(struct __DCSDictionary *)arg1;
- (id)description;
@property BOOL focused; // @synthesize focused=_focused;

@end

