/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSTableView;

@interface DSIndexHeaderCell : NSTextFieldCell
{
    NSTableView *_relatedTableView;
}

- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property NSTableView *relatedTableView; // @synthesize relatedTableView=_relatedTableView;

@end

