/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableView.h"

@interface DSIndexTableView : NSTableView
{
    BOOL _showingSpellCorrectedWords;
}

- (void)drawBackgroundInClipRect:(struct CGRect)arg1;
- (void)highlightSelectionInClipRect:(struct CGRect)arg1;
@property BOOL showingSpellCorrectedWords; // @synthesize showingSpellCorrectedWords=_showingSpellCorrectedWords;

@end

