/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSBox, NSButton, NSPanel, NSString;

@interface DictionaryConverter : NSObject
{
    NSPanel *_convertPanel;
    NSButton *_convertBtn;
    NSBox *_locationOptionArea;
    NSBox *_copyOptionArea;
    NSString *_sourceFilePath;
    int _installLocation;
    int _copyDataFile;
    BOOL _copyStarted;
    BOOL _copying;
    BOOL _installingDictionary;
    NSString *_dictionaryName;
    NSString *_targetPath;
    BOOL _notifyCopyFinished;
    int _error;
}

- (id)initWithFile:(id)arg1;
- (id)installDictionaryWithConfirm:(BOOL)arg1 alreadyExist:(BOOL)arg2;
- (void)convert:(id)arg1;
- (void)cancel:(id)arg1;
- (void)_copyDataFile:(id)arg1;

@end

