/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class MetalTabLabelView, NSBox, NSMutableArray, NSTabView, NSTextField, SlidingAnimation;

@interface MetalTabHeaderView : NSView
{
    NSTabView *_tabView;
    id _delegate;
    MetalTabLabelView *_tabLabelTemplate;
    NSTextField *_clipMark;
    NSBox *_limitBox;
    NSMutableArray *_tabLabelList;
    int _tabCount;
    int _visibleTabCount;
    int _selectedTabIndex;
    int _firstLabelOffsetX;
    int _lastLabelEndX;
    int _maxLabelWidth;
    int _minLabelWidth;
    BOOL _autodisplay;
    BOOL _callByMyself;
    BOOL _temporaryMouseOverFlag;
    NSMutableArray *_mouseTrackIDList;
    SlidingAnimation *_animationController;
    BOOL _draggingLabel;
}

+ (id)_backgroundShadeColor;
+ (id)_mouseOverShadeColor;
+ (id)_darkFrameColor;
+ (id)_lightFrameColor;
- (void)awakeFromNib;
- (void)dealloc;
- (id)tabView;
- (void)setTabView:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setAutodisplay:(BOOL)arg1;
- (id)labelViewForTabViewItem:(id)arg1;
- (id)tabViewItemForLabelView:(id)arg1;
- (id)orderedTabViewItems;
- (void)setHidden:(BOOL)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct _NSSize)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)mouseDown:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (BOOL)tabView:(id)arg1 shouldSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 willSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabViewDidChangeNumberOfTabViewItems:(id)arg1;
- (void)tabLabelView:(id)arg1 didChangeLabel:(id)arg2;
- (void)_startDraggingTabLabel:(id)arg1 withEvent:(id)arg2;
- (void)_slideLabelsForMovingLabel:(id)arg1 from:(int)arg2 to:(int)arg3;
- (void)_selectLabelView:(id)arg1;
- (void)_selectTabViewItemForLabelView:(id)arg1;
- (void)_syncSelectionWithTabView;
- (id)_addTabLabelWithTabViewItem:(id)arg1 display:(BOOL)arg2;
- (void)_removeTabLabel:(id)arg1 display:(BOOL)arg2;
- (id)_generateTabLabelFromTemplate;
- (void)_showClippedTabMenu:(id)arg1;
- (void)selectClippedTabMenu:(id)arg1;
- (void)_rearrangeLabels;
- (void)_resetMouseTrackRectForLabels;
- (void)_drawBackgroundForLabel:(id)arg1 clipRect:(struct _NSRect)arg2;
- (struct _NSRect)_updateRectForLabel:(id)arg1;
- (struct _NSRect)_headerRectForLabel:(id)arg1;
- (id)_labelViewForPoint:(struct _NSPoint)arg1;
- (void)_drawSeparatorAt:(float)arg1 dark:(BOOL)arg2;
- (void)tabHeaderView:(id)arg1 didShowHide:(BOOL)arg2 delta:(float)arg3;

@end

