/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (CocoaExtensions)
+ (id)stringWithFourCharCode:(unsigned long)arg1;
- (unsigned long)fourCharCodeValue;
- (id)attributedStringForTruncation:(unsigned int)arg1;
- (int)commonPrefixLength:(id)arg1;
- (id)normalizedKey;
- (int)normalizedKeyCompare:(id)arg1;
- (int)normalizedKeyCompare:(id)arg1 range:(struct _NSRange)arg2;
@end

