/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTableView.h"

@interface PrefDictionaryTableView : NSTableView
{
}

- (void)rightMouseDown:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)_editDictionaryLabel:(id)arg1;
- (void)_revertDictionaryLabel:(id)arg1;

@end

