/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WebView.h"

@interface WebView (DictionaryExtensions)
- (void)setScrollersConfigWithSize:(unsigned int)arg1;
- (BOOL)processKeyCommand:(SEL)arg1;
- (BOOL)hasSelection;
- (id)webFrameHasSelection;
- (BOOL)jumpToSelection;
- (id)selectedString;
- (struct _NSRect)selectionScreenRect;
- (float)scrollPositionFromTopOfPage;
- (void)setScrollPositionToOffsetInPage:(float)arg1;
- (void)forceLayoutAllFrames;
- (BOOL)frameIsVisible:(id)arg1;
- (id)longestTermAtLocation:(struct _NSPoint)arg1 domRange:(id *)arg2;
- (BOOL)isLocation:(struct _NSPoint)arg1 inDOMRange:(id)arg2;
- (id)textAtScreenLocation:(struct _NSPoint)arg1;
- (BOOL)screenLocationInSelection:(struct _NSPoint)arg1;
@end

