/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindow.h"

@class DictionaryWindowTitleCell, NSString;

@interface DictionaryBrowserWindow : NSWindow
{
    NSString *_dictionaryName;
    DictionaryWindowTitleCell *_customTitleCell;
}

- (void)dealloc;
- (id)_customTitleCell;
@property(retain) NSString *dictionaryName; // @synthesize dictionaryName=_dictionaryName;

@end

