/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSArray.h"

@class NSMutableArray;

@interface DictionaryRecordArray : NSArray
{
    struct __CFArray *_originalArray;
    NSMutableArray *_objShadowOwner;
}

- (id)initWithCFArray:(struct __CFArray *)arg1;
- (id)initWithNSArray:(id)arg1;
- (void)addRecordsFromRecordArray:(id)arg1;
- (void)dealloc;
- (unsigned long long)count;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (struct __CFArray *)_originalArray;
- (id)_shadowArray;

@end

