/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton, NSMutableArray, NSPopUpButton;

@interface DictionaryScopeBar : NSView
{
    NSPopUpButton *_clipMark;
    NSButton *_templateButton;
    id _actionTarget;
    SEL _actionSelector;
    long long _selectedIndex;
    NSMutableArray *_buttons;
    int _hiddenButtonCount;
    id _axLinkedElement;
}

- (void)awakeFromNib;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (long long)tag;
- (void)setAction:(SEL)arg1 target:(id)arg2;
@property long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property id axLinkedElement; // @synthesize axLinkedElement=_axLinkedElement;
- (long long)tagForIndex:(long long)arg1;
- (void)addButtonTitle:(id)arg1 tag:(long long)arg2 contextMenu:(id)arg3;
- (void)clearButtons;
- (void)clipMarkPopupMenuSelected:(id)arg1;
- (void)_buttonSelected:(id)arg1;
- (void)_setButtonAttributes:(id)arg1 tag:(long long)arg2;
- (void)_setButtonAXLinkedElement:(id)arg1;
- (void)_recalcButtonsVisibility;
- (void)_clippedPopupMenuWillSelect:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;

@end

