/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WebView.h"

@interface WebView (DictionaryExtensions)
- (void)setScrollersConfigWithSize:(unsigned long long)arg1;
- (BOOL)processKeyCommand:(SEL)arg1;
- (BOOL)hasSelection;
- (id)webFrameHasSelection;
- (BOOL)jumpToSelection;
- (id)selectedString;
- (struct CGRect)selectionScreenRect;
- (double)scrollPositionFromTopOfPage;
- (void)setScrollPositionToOffsetInPage:(double)arg1;
- (void)setAllowAnimationScroll:(BOOL)arg1;
- (void)forceLayoutAllFrames;
- (BOOL)frameIsVisible:(id)arg1;
- (BOOL)frameIsValid:(id)arg1;
- (id)longestTermAtLocation:(struct CGPoint)arg1 domRange:(id *)arg2;
- (BOOL)isLocation:(struct CGPoint)arg1 inDOMRange:(id)arg2;
@end

