/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSButton.h"

@class NSMenu;

@interface DictionaryScopeBarButton : NSButton
{
    NSMenu *_contextMenu;
    id _representedObject;
}

@property(retain) id representedObject; // @synthesize representedObject=_representedObject;
@property(retain) NSMenu *contextMenu; // @synthesize contextMenu=_contextMenu;
- (id)menuForEvent:(id)arg1;
- (void)dealloc;

@end

