/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSPageControllerDelegate-Protocol.h"

@class NSPageController;

@interface DictionaryHistory : NSObject <NSPageControllerDelegate>
{
    NSPageController *_pageController;
    id <DictionaryHistoryDelegate> _delegate;
    BOOL _settingForwardObject;
    BOOL _needToHideHistoryTransition;
    BOOL _delayHideHistoryTransition;
    BOOL _needToUpdateDiaplayEndTransition;
}

@property(nonatomic) id <DictionaryHistoryDelegate> delegate; // @synthesize delegate=_delegate;
- (void)pageControllerDidEndLiveTransition:(id)arg1;
- (void)pageController:(id)arg1 didTransitionToObject:(id)arg2;
- (void)pageControllerWillStartLiveTransition:(id)arg1;
- (void)_debugPrintHistoryInfo;
- (void)_checkNextItemIsNull;
- (void)completeTransition;
- (void)setSelectedHistoryIndex:(long long)arg1 withAnimation:(BOOL)arg2;
- (long long)selectedHistoryIndex;
- (id)historyItemsArray;
- (void)setCurrentHistoryToNUll;
- (void)clearAllHistoryItems;
- (void)setForwardHistoryItem:(id)arg1;
- (void)setCurrentHistoryItem:(id)arg1;
- (id)currentHistoryItem;
- (void)dealloc;
- (id)initWithPageContoller:(id)arg1;
- (id)initWithPageView:(id)arg1;

@end

