/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton, NSMutableArray;

@interface DictionaryFilterView : NSView
{
    NSView *_clipMark;
    NSButton *_templateButton;
    id _actionTarget;
    SEL _actionSelector;
    long long _selectedIndex;
    NSMutableArray *_buttons;
    int _hiddenButtonCount;
}

- (void)awakeFromNib;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseDown:(id)arg1;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (long long)tag;
- (void)setAction:(SEL)arg1 target:(id)arg2;
- (long long)selectedIndex;
- (void)setSelectedIndex:(long long)arg1;
- (long long)tagForIndex:(long long)arg1;
- (void)addButtonTitle:(id)arg1 tag:(long long)arg2 contextMenu:(id)arg3;
- (void)clearButtons;
- (void)_buttonSelected:(id)arg1;
- (void)_setButtonAttributes:(id)arg1 tag:(long long)arg2;
- (void)_recalcButtonsVisibility;
- (void)_showClippedButtonMenu:(id)arg1;
- (void)_selectClippedButtonMenu:(id)arg1;

@end

