/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DictionaryBook, DictionaryRecordRepository, DictionaryWebView, NSArray, NSArrayController, NSColor, NSMutableArray, NSMutableDictionary, NSScrollView, NSString;

@interface DictionaryController : NSObject
{
    DictionaryWebView *_descriptionWebView;
    NSScrollView *_foundIndexScrollView;
    NSArrayController *_foundArrayController;
    id _delegate;
    DictionaryBook *_dictionaryBook;
    unsigned long long _findMethod;
    NSString *_lastSearchText;
    NSString *_lastSelectedKeyString;
    DictionaryRecordRepository *_foundRecords;
    NSMutableArray *_foundKeywordArray;
    NSArray *_fullSearchResult;
    NSColor *_foundWordColor;
    unsigned long long _lastSelectedIndex;
    BOOL _updateIndex;
    double _minIndexViewWidth;
    double _lastIndexViewWidth;
    BOOL _showIndexWithTable;
    NSMutableDictionary *_loadingFrameNames;
    double _restoringScrollPosFromSnapshot;
    BOOL _useParentalControl;
    BOOL _useMouseoverLink;
    NSString *_lastPointedTerm;
    NSString *_lastClickedTerm;
    id _lastDOMRange;
    unsigned long long _lastClickedModifiers;
    NSMutableDictionary *_lastXMLDocumentsForDisplay;
    NSArray *_lastRecordsForDictionarySwitch;
    NSString *_lastIndexlabel;
    NSMutableDictionary *_lastAnchorNamesForFrame;
    double _indexFontSize;
    double _indexDefaultRowHeight;
    double _indexDefaultFontSize;
    struct CGSize _indexDefaultSpacing;
    BOOL _changingSelectionByCode;
    BOOL _clickedIndexLabel;
    BOOL _processedKeyEvent;
    BOOL _keyEventCheckMode;
    SEL _keyEventCheckResult;
    BOOL _rewindingHistory;
    BOOL _loadingWebView;
    BOOL _resumingCache;
    NSString *_lastMouseoverLink;
    int _popupLinkWindowState;
    BOOL _loadIsRunning;
    NSMutableDictionary *_delayedSubFrameProcessors;
}

- (id)initWithTitle:(id)arg1;
- (id)initWithBook:(id)arg1;
- (id)initWithProperty:(id)arg1;
- (id)_convertPropertyIfNeeded:(id)arg1;
- (id)retrieveProperty;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (BOOL)processedSpecialEvent:(id)arg1;
- (void)_jumpToClickedTerm;
- (id)dictionaryBook;
- (void)setDictionaryBook:(id)arg1;
- (long long)focusedDictionaryIndexForUI;
- (void)revealedWithContents:(BOOL)arg1 withTextSizeMultiplier:(double)arg2;
- (unsigned long long)updateFoundListForKey:(id)arg1 byMethod:(unsigned long long)arg2 withSelection:(id)arg3;
- (id)foundRecordsForKey:(id)arg1 byMethod:(unsigned long long)arg2 maxRecordForEach:(long long)arg3;
- (id)_findKeyInternal:(id)arg1 byMethod:(unsigned long long)arg2 maxRecordForEach:(long long)arg3 withSelection:(id)arg4 updateIndexList:(BOOL)arg5;
- (id)foundRecords;
- (void)updateIndexListWithFoundRecords:(id)arg1 lastFindMethod:(unsigned long long)arg2 lastSearchKey:(id)arg3 withSelection:(id)arg4 drawDescription:(BOOL)arg5;
- (void)updateIndexListFromSnapshot:(id)arg1;
- (void)updateContentsFromSnapshot:(id)arg1;
- (void)updateContentsForDictionarySwitch;
- (void)updateContentsWithDealyedFoundRecords:(id)arg1 forDictionary:(id)arg2 allFoundRecords:(id)arg3;
- (void)prepareForNewSearch:(id)arg1 clearList:(BOOL)arg2;
- (void)showFrontMatterOfDictionary:(id)arg1;
- (void)_switchDictionaryScope:(long long)arg1;
- (void)_leaveCurrentDisplay;
- (void)_setFoundRecords:(id)arg1;
- (void)_setFoundKeywordArray:(id)arg1;
- (void)_displayContents:(id)arg1 forRecords:(id)arg2 withSelection:(id)arg3;
- (id)_generateMainFrameString;
- (BOOL)_updateLoadingData:(id)arg1 forRecords:(id)arg2;
- (void)_adjustXMLDocuments:(id)arg1;
- (void)_loadContentsInFrame:(id)arg1;
- (void)printContents;
- (BOOL)lockingContentsForPrint;
- (void)dictSchemeHandlerForURL:(id)arg1 withLabel:(id)arg2 fromReferer:(id)arg3;
- (void)dictHandlerForStringLongest:(id)arg1 withLabel:(id)arg2 inDictionary:(id)arg3;
- (void)setIndexSelection:(unsigned long long)arg1 absolute:(BOOL)arg2;
- (void)confirmIndexSelection;
- (void)showHideFullSearchView:(BOOL)arg1;
- (double)changeTextSize:(BOOL)arg1 limitted:(char *)arg2;
- (BOOL)findOnDirection:(BOOL)arg1 withKeyWord:(id)arg2;
- (BOOL)jumpToSelection;
- (BOOL)hasSelection;
- (id)selectedStringForFindPanel;
- (void)_changeIndexTextSize:(id)arg1;
- (id)_indexTableView;
- (void)_tableViewDoubleClicked:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)_dictselectSchemeHandlerForIdentifier:(id)arg1 withFlag:(BOOL)arg2;
- (void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)_lookupInNewWindow:(id)arg1;
- (void)_openLinkInNewWindow:(id)arg1;
- (unsigned long long)webView:(id)arg1 dragDestinationActionMaskForDraggingInfo:(id)arg2;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2;
- (BOOL)_processKeyEvent:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)insertText:(id)arg1;
- (void)_displayIndexSearchSelectionAndTakeSnapshot:(BOOL)arg1;
- (void)_displayIndexSearchSelection;
- (void)_displayLinkForKey:(id)arg1 headword:(id)arg2 dictionary:(id)arg3 anchor:(id)arg4 flag:(unsigned int)arg5 returnable:(BOOL)arg6;
- (void)_displayKey:(id)arg1 data:(id)arg2 forRecords:(id)arg3 selection:(id)arg4 referrer:(id)arg5 reflectSearchField:(BOOL)arg6 takeSnapshot:(BOOL)arg7;
- (void)_takeSnapshotCurrentContents:(id)arg1 selection:(id)arg2 referrer:(id)arg3 reflectSearchField:(BOOL)arg4;
- (void)_addSpellCorrectedMarkToSnapshot:(id)arg1;
- (id)_searchFieldTextForSelectedIndexTitle:(id)arg1;
- (id)_focusedDictionary;
- (id)_focusedDictionaryID;
- (id)_dataForIndexWord:(id)arg1 withKeyString:(id)arg2 inRecords:(id)arg3 foundRecords:(id *)arg4;
- (id)_resolveLinkedRecordForKey:(id)arg1 anchor:(id)arg2 flag:(unsigned int)arg3 resolvedRecords:(id *)arg4;
- (void)_showSplashPage;
- (void)_displayLinkForURL:(id)arg1 withLabel:(id)arg2 returnable:(BOOL)arg3;
- (id)_tagsForEnumedWords;
- (void)_setNewFindMethod:(unsigned long long)arg1;
- (id)_normalizeSpellCorrectedWord:(id)arg1;
- (void)_clearContentsOfFrame:(id)arg1;
- (void)_delayedSubFrameFormatting:(id)arg1;
- (void)webView:(id)arg1 didHandleOnloadEventsForFrame:(id)arg2;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)_formatFrame:(id)arg1 withScriptObject:(id)arg2 loadFinished:(BOOL)arg3;
- (void)_finishLoadingAllFrameContents;
- (void)_saveCurrentScrollPosWithCreatingSnapshot:(BOOL)arg1;
- (void)_cacheRemoteContents;
- (BOOL)_findIndexListOnDirection:(BOOL)arg1 withKeyWord:(id)arg2;
- (BOOL)_findWebViewOnDirection:(BOOL)arg1 withKeyWord:(id)arg2;
- (BOOL)_isShowingIndexList;
- (void)dictionaryController:(id)arg1 didSelectRecord:(id)arg2 reflectSearchField:(BOOL)arg3;
- (void)dictionaryController:(id)arg1 snapCurrentScrollPosition:(double)arg2 forScope:(long long)arg3 create:(BOOL)arg4;
- (void)dictionaryController:(id)arg1 cacheRemoteContents:(id)arg2 forDictionary:(id)arg3;
- (void)dictionaryController:(id)arg1 didShowHideIndex:(BOOL)arg2;
- (void)dictionaryController:(id)arg1 suggestUnknownWord:(id)arg2;
- (void)dictionaryControllerDidCancelAsyncFind:(id)arg1;
- (void)dictionaryControllerIndexSelectionWasChanged:(id)arg1;
- (void)dictionaryControllerDidClearPreviousResult:(id)arg1;
- (void)dictionaryController:(id)arg1 saveResumeCache:(BOOL)arg2 forDictionary:(id)arg3;

@end

