/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface DictionaryRecord : NSObject
{
    struct __DCSRecord *_recordRef;
    NSString *_additionalAnchor;
    unsigned char _censorFlag;
}

- (id)initWithDCSRecordRef:(struct __DCSRecord *)arg1;
- (void)dealloc;
- (id)keyword;
- (id)headword;
- (id)rawHeadword;
- (id)title;
- (void)setAnchor:(id)arg1;
- (id)anchor;
- (id)dictionary;
- (id)parentDictionary;
- (id)subDictionary;
- (id)dataURL;
- (id)contentsForStyle:(long long)arg1;
- (struct __DCSRecord *)_DCSRecordRef;
@property unsigned char censorFlag; // @synthesize censorFlag=_censorFlag;

@end

