/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError, NSString;

@interface DSDictionaryObj : NSObject
{
    struct __DCSDictionary *_dictionaryRef;
    unsigned int _indexID;
    BOOL _inFocus;
    NSString *_customLabelName;
    NSString *_modifiedIdentifer;
    NSError *_lastError;
}

+ (void)registerSubClassName:(id)arg1;
+ (BOOL)handleThisDCSDictionaryRef:(struct __DCSDictionary *)arg1;
+ (id)availableDictionaries;
+ (id)activeDictionaries;
+ (id)dictionaryWithDCSDictionaryRef:(struct __DCSDictionary *)arg1;
+ (id)dictionaryWithIdentifier:(id)arg1;
+ (id)dictionaryWithPath:(id)arg1;
+ (long long)defaultFoundCountCap;
- (id)_initWithDCSDictionaryRef:(struct __DCSDictionary *)arg1;
- (void)dealloc;
- (id)dictionaryPath;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)copyright;
- (id)contentsBaseURL;
- (id)cssFileURL;
- (BOOL)isLocalDictionary;
- (id)infoDictionary;
- (struct __DCSDictionary *)dictionaryRef;
- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (id)parent;
- (id)children;
- (id)labelName;
- (void)setLabelName:(id)arg1;
- (id)customLabelName;
- (id)prefsHTMLString;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)appSpecificSettingForKey:(id)arg1;
- (void)setAppSpecificSetting:(id)arg1 forKey:(id)arg2;
- (id)findKey:(id)arg1 byMethod:(unsigned long long)arg2 maxRecord:(long long)arg3;
- (id)findByReferenceID:(id)arg1;
- (id)dataStringForRecord:(id)arg1;
- (long long)foundCountCap;
- (id)noEntriesFoundString;
- (id)postProcessScriptForFrame:(id)arg1 loadFinished:(char *)arg2;
- (void)_setDCSDictionaryRef:(struct __DCSDictionary *)arg1;
- (id)description;
@property BOOL inFocus; // @synthesize inFocus=_inFocus;
@property unsigned int indexID; // @synthesize indexID=_indexID;

@end

