/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

@class DSImageView, NSURL, NSWindow;

@interface ImageWindowController : NSWindowController
{
    DSImageView *_imageView;
    NSURL *_imageURL;
    NSWindow *_parentWindow;
    BOOL _positioningWindow;
    BOOL _zoomingWindow;
}

+ (id)createImageWindowForURL:(id)arg1 withTitle:(id)arg2 fromWindow:(id)arg3;
+ (void)setDefaultImageSize:(struct CGSize)arg1;
- (BOOL)setImageURL:(id)arg1 andTitle:(id)arg2;
- (void)dealloc;
- (void)windowWillClose:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)windowWillMiniaturize:(id)arg1;
- (void)windowDidDeminiaturize:(id)arg1;
- (BOOL)windowShouldZoom:(id)arg1 toFrame:(struct CGRect)arg2;
- (void)_setParentWindow:(id)arg1;
- (void)_positionWindow;
- (BOOL)_tryToLocateWindow:(struct CGRect *)arg1 withLastParentFrame:(struct CGRect)arg2 preferVerticalAlign:(BOOL)arg3 strictly:(BOOL)arg4;

@end

