/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface ApplicationController : NSObject
{
    NSMutableArray *_availableDictionaries;
    BOOL _appInitializeDone;
}

+ (id)sharedAppController;
- (void)awakeFromNib;
- (void)applicationDidFinishLaunching:(id)arg1;
- (id)_prepareMyPreferences;
- (void)_delayedDidFinishLaunching;
- (BOOL)applicationShouldOpenUntitledFile:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (BOOL)_handleSearchTextAppleEvent;
- (void)applicationWillTerminate:(id)arg1;
- (void)showAboutBox:(id)arg1;
- (void)newBrowserWindow:(id)arg1;
- (void)selectDictionary:(id)arg1;
- (void)backHistory:(id)arg1;
- (void)forwardHistory:(id)arg1;
- (void)selectNextDictionary:(id)arg1;
- (void)selectPrevDictionary:(id)arg1;
- (void)showPreferences:(id)arg1;
- (void)doPageSetup:(id)arg1;
- (void)doPrint:(id)arg1;
- (void)selectSearchField:(id)arg1;
- (id)availableDictionaries;
- (void)setAvailableDictionaries:(id)arg1;
- (void)upodateDictionaries:(id)arg1 inWindow:(id)arg2;
- (void)updateScopebarForAllWindows;
- (void)saveWindowStatesWithSettings:(BOOL)arg1 afterDelay:(double)arg2;
- (void)updatePreference;
- (void)clearWebKitCacheDebug:(id)arg1;
- (void)activeDictionariesDidChanged:(id)arg1;
- (BOOL)panel:(id)arg1 shouldShowFilename:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (id)_dictionaryWindowList;
- (void)_saveWindowStatesWithSettings:(id)arg1;
- (BOOL)_restoreSavedWindows:(id)arg1 foundNewDicts:(char *)arg2;
- (id)_convertToChildrenDictionaryArray:(id)arg1;
- (long long)_generateWindowIDForWindow:(id)arg1;
- (BOOL)_shouldOpenNewWindowForExternalRequest;
- (void)doLookupService:(id)arg1 userData:(id)arg2 error:(id *)arg3;
- (void)application:(id)arg1 runTest:(unsigned long long)arg2 duration:(double)arg3;

@end

