/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSWindowController.h"

@class DictionaryController, DictionaryScopeBar, DictionarySearchField, NSDictionary, NSMutableArray, NSObjectController, NSPrintInfo, NSProgressIndicator, NSSegmentedControl, NSTextField, NSWindow;

@interface BrowserWindowController : NSWindowController
{
    NSSegmentedControl *_backForwardBtn;
    NSSegmentedControl *_textSizeBtn;
    NSWindow *_dictionaryLabelSheet;
    NSTextField *_dictionaryLabelField;
    DictionarySearchField *_searchField;
    NSProgressIndicator *_searchProgressSpinner;
    DictionaryScopeBar *_scopeBar;
    NSObjectController *_dictionaryControllerController;
    DictionaryController *_dictionaryController;
    long long _selectedDictionaryIndex;
    NSMutableArray *_historyRecords;
    long long _historyPosition;
    NSDictionary *_reproducingSnapShot;
    NSMutableArray *_queuedAlertRequests;
    double _textSizeMultiplier;
    struct CGRect _imageWindowFrame;
    struct CGRect _imageWindowParentFrame;
    BOOL _disableResumeCache;
    long long _windowID;
    BOOL _rewindingHistory;
    BOOL _resumingCache;
    NSPrintInfo *printInfo;
    BOOL _isInSelfTest;
}

+ (id)activeWindowController;
+ (id)defaultWindowTitle;
+ (void)validateAllMenuEquivalents;
+ (void)_reinitializeSearchMenu;
+ (BOOL)_reinitializeFrontMatterMenu;
- (void)setupWithDictionaryList:(id)arg1;
- (BOOL)setupWithProperty:(id)arg1 frame:(id)arg2;
- (id)retrieveProperty;
- (void)windowDidLoad;
- (void)dealloc;
- (void)showWindow:(id)arg1;
- (void)backOrForward:(id)arg1;
- (void)backHistory:(id)arg1;
- (void)forwardHistory:(id)arg1;
- (void)backOrForwardMenu:(id)arg1;
- (void)chooseDictionary:(id)arg1;
- (void)changeTextSize:(id)arg1;
- (void)showFrontMatterPage:(id)arg1;
- (void)setSearchStringValue:(id)arg1 displayString:(id)arg2 triggerSearch:(BOOL)arg3;
- (void)showRequestedURL:(id)arg1 label:(id)arg2;
- (void)showRequestedStringLongest:(id)arg1 inDictionary:(id)arg2;
- (void)setSelectedDictionaryIndex:(long long)arg1;
- (void)toggleDictionary:(BOOL)arg1;
- (void)updateScopebar;
- (void)startProgressAnimation;
- (void)stopProgressAnimation;
- (id)dictionaryList;
- (void)setDictionaryList:(id)arg1;
- (void)addDictionary:(id)arg1;
- (BOOL)processedSpecialEvent:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)imageWindowFrame:(struct CGRect *)arg1 onParentFrame:(struct CGRect *)arg2;
- (void)setImageWindowFrame:(struct CGRect)arg1;
- (id)contextualMenuForDictionary:(id)arg1 target:(id)arg2 editAction:(SEL)arg3 revertAction:(SEL)arg4;
- (void)historyAvailableForBack:(char *)arg1 forward:(char *)arg2;
- (void)clearHistories;
- (id)printInfo;
- (void)setPrintInfo:(id)arg1;
- (void)printInfoUpdated;
- (void)doPageLayout;
- (void)didEndPageLayout:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)printContents;
- (BOOL)hasSearchedText;
- (BOOL)hasInlineInputArea;
- (void)setWindowID:(long long)arg1;
- (long long)windowID;
- (void)dictionarySearchFieldStringDidChanged:(id)arg1;
- (void)dictionarySearchFieldMethodDidChanged:(id)arg1;
- (void)dictionarySearchFieldConfirmed:(id)arg1;
- (void)dictionaryController:(id)arg1 didSelectRecord:(id)arg2 reflectSearchField:(BOOL)arg3;
- (void)dictionaryController:(id)arg1 snapCurrentIndexScrollPos:(double)arg2 contentsScrollPos:(double)arg3 forScope:(long long)arg4 create:(BOOL)arg5;
- (void)dictionaryController:(id)arg1 saveResumeCache:(BOOL)arg2 forDictionary:(id)arg3;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)runDefaultTestSuite:(id)arg1;
- (void)runPerformanceTest:(id)arg1;
- (BOOL)isInSelfTest;
- (void)setSelfTestFlag:(BOOL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)_snapback:(id)arg1;
- (void)_addSnapshot:(id)arg1 checkDuplicate:(BOOL)arg2;
- (void)_setSelectionToHistory:(id)arg1;
- (void)_backOrForwardHistory:(long long)arg1;
- (void)_reproduceSnapshot:(id)arg1;
- (void)_removeHistoryOfBook:(id)arg1;
- (void)_updateBackForwardMenuAt:(long long)arg1;
- (id)_createMenuFromArray:(id)arg1 startIndex:(long long)arg2 forBack:(BOOL)arg3;
- (BOOL)_isEqualWithLastSnapshot:(id)arg1;
- (void)_setTimerForSavingCurrentSearchString:(BOOL)arg1;
- (void)_saveCurrentSearchStringForResume;
- (id)_loadResumeCacheData;
- (id)_resumeCacheURLWithFolderCreation:(BOOL)arg1;
- (void)_changeTextSize:(BOOL)arg1;
- (void)_chooseDictionaryByDictionaryIndex:(long long)arg1;
- (id)_dictionaryController;
- (void)_updateDictionaryController;
- (void)_editDictionaryLabel:(id)arg1;
- (void)_editLabelSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)closeEditLabelSheet:(id)arg1;
- (void)_revertDictionaryLabel:(id)arg1;
- (void)_updateWindowTitle:(id)arg1;
- (void)_showAlertFromDictionary:(id)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_setAccessibilityDescription:(id)arg1 forControl:(id)arg2 segment:(long long)arg3;

@end

