/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSSearchFieldCell.h"

@class DictionarySearchFieldEditor, NSButtonCell;

@interface DictionarySearchFieldCell : NSSearchFieldCell
{
    DictionarySearchFieldEditor *_customEditor;
    NSButtonCell *_snapbackButtonCell;
}

- (void)dealloc;
- (id)fieldEditorForView:(id)arg1;
- (id)_snapbackCell;

@end

