/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WebKit/WebView.h"

@interface DictionaryWebView : WebView
{
    BOOL _nowPrinting;
    BOOL _printingAllView;
    struct CGSize _savedFrameSize;
    double _savedFrameMargin;
}

- (void)_adjustPrintingMarginsForHeaderAndFooter;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)printContentsInFrame:(id)arg1 jobTitle:(id)arg2;
- (BOOL)lockingContentsForPrint;
- (void)_printOperationDidRun:(id)arg1 success:(BOOL)arg2 contextInfo:(void *)arg3;

@end

