/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface ApplicationController : NSObject
{
    NSMutableArray *_availableDictionaries;
    BOOL _showIndexWithTable;
    BOOL _useTab;
    BOOL _useMultiWindow;
}

+ (id)sharedAppController;
- (void)awakeFromNib;
- (void)applicationDidFinishLaunching:(id)arg1;
- (id)_prepareMyPreferences;
- (void)_delayedDidFinishLaunching;
- (BOOL)applicationShouldOpenUntitledFile:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (BOOL)_handleSearchTextAppleEvent;
- (void)applicationWillTerminate:(id)arg1;
- (void)showAboutBox:(id)arg1;
- (void)newBrowserWindow:(id)arg1;
- (void)addDictionaryTab:(id)arg1;
- (void)selectDictionary:(id)arg1;
- (void)removeDictionaryTab:(id)arg1;
- (void)backHistory:(id)arg1;
- (void)forwardHistory:(id)arg1;
- (void)chooseDictionary:(id)arg1;
- (void)selectNextDictionary:(id)arg1;
- (void)selectPrevDictionary:(id)arg1;
- (void)showDictionarySettings:(id)arg1;
- (void)showPrevDictionaryTab:(id)arg1;
- (void)showNextDictionaryTab:(id)arg1;
- (void)showPreferences:(id)arg1;
- (void)doPageSetup:(id)arg1;
- (void)doPrint:(id)arg1;
- (void)selectSearchField:(id)arg1;
- (BOOL)showIndexWithTable;
- (id)availableDictionaries;
- (void)setAvailableDictionaries:(id)arg1;
- (void)upodateCurrentBookWithDictionaries:(id)arg1;
- (void)clearWebKitCacheDebug:(id)arg1;
- (void)activeDictionariesDidChanged:(id)arg1;
- (BOOL)panel:(id)arg1 shouldShowFilename:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (id)_dictionaryWindowList;
- (BOOL)_restoreSavedWindows:(id)arg1 foundNewDicts:(char *)arg2;
- (void)_checkMountedDrives;
- (void)deviceMounted:(id)arg1;
- (id)_catalogPathForEPWINGContainer:(id)arg1;
- (void)_installDictionaryAtPath:(id)arg1 confirm:(BOOL)arg2;
- (void)_addToUseNewDictionary:(id)arg1;
- (void)_showDictionaryInstalledMessage:(id)arg1;
- (void)doLookupService:(id)arg1 userData:(id)arg2 error:(id *)arg3;
- (BOOL)_activateDictionaryServiceComponent;
- (struct __TSMInputSource *)_createDictionaryServiceInputSource;
- (void)application:(id)arg1 runTest:(unsigned int)arg2 duration:(double)arg3;

@end

