/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

@class DelayedMenuSegmentedControl, DictionaryController, DictionaryFilterView, DictionarySearchFieldEditor, MetalTabHeaderView, NSDictionary, NSFont, NSMutableArray, NSPrintInfo, NSProgressIndicator, NSSearchField, NSSegmentedControl, NSString, NSTabViewItem, NSTextField, NSView, NSWindow;

@interface BrowserWindowController : NSWindowController
{
    DelayedMenuSegmentedControl *_backForwardBtn;
    NSSegmentedControl *_textSizeBtn;
    MetalTabHeaderView *_tabHeaderView;
    NSTabViewItem *_tabItemTemplate;
    NSWindow *_dictionarySettingSheet;
    NSTextField *_dictionarySetNameField;
    NSWindow *_dictionaryLabelSheet;
    NSTextField *_dictionaryLabelField;
    NSSearchField *_searchField;
    NSProgressIndicator *_searchProgressSpinner;
    NSView *_toolbarView;
    DictionaryFilterView *_scopeBar;
    id _showIndexSwitch;
    NSString *_searchText;
    unsigned int _searchMethod;
    NSMutableArray *_historyRecords;
    int _historyPosition;
    NSDictionary *_reproducingSnapShot;
    DictionaryController *_activeBookController;
    NSMutableArray *_bookControllerList;
    NSMutableArray *_queuedAlertRequests;
    int _progressAnimationLevel;
    float _textSizeMultiplier;
    struct _NSRect _imageWindowFrame;
    struct _NSRect _imageWindowParentFrame;
    float _indexWidthBeforeFullSearch;
    BOOL _showIndex;
    int _selectedDictionaryIndex;
    BOOL _changingTabByMyself;
    BOOL _changingSearchTextByMyself;
    BOOL _rewindingHistory;
    BOOL _fullTextSearching;
    BOOL _frontMatterMenuItemEnabled;
    BOOL _showIndexWithTable;
    DictionarySearchFieldEditor *_searchFieldEditor;
    NSMutableArray *_dictionariesWithFlags;
    NSFont *_copyrightFont;
    NSPrintInfo *printInfo;
    BOOL _isInSelfTest;
}

+ (id)activeWindowController;
+ (id)defaultWindowTitle;
- (void)windowDidLoad;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)dealloc;
- (void)showWindow:(id)arg1;
- (void)_showAlertFromDictionary:(id)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (int)countBook;
- (id)tabHeaderView;
- (id)bookForCurrentTab;
- (void)setBookToCurrentTab:(id)arg1;
- (void)addDictionaryToCurrentTab:(id)arg1;
- (void)addTabWithBook:(id)arg1 showTab:(BOOL)arg2 editLabel:(BOOL)arg3;
- (BOOL)setupWithProperty:(id)arg1;
- (void)_setBookControllerToCurrentTab:(id)arg1;
- (id)retrieveProperty;
- (BOOL)processedSpecialEvent:(id)arg1;
- (void)removeCurrentTab;
- (void)showPrevNextTab:(BOOL)arg1;
- (void)showDictionarySettings;
- (void)_dictSettingSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)closeDictionarySettingSheet:(id)arg1;
- (void)showRequestedURL:(id)arg1;
- (void)showRequestedStringLongest:(id)arg1 inDictionary:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)startProgressAnimation;
- (void)stopProgressAnimation:(BOOL)arg1;
- (void)historyAvailableForBack:(char *)arg1 forward:(char *)arg2;
- (void)imageWindowFrame:(struct _NSRect *)arg1 onParentFrame:(struct _NSRect *)arg2;
- (void)setImageWindowFrame:(struct _NSRect)arg1;
- (void)setSearchText:(id)arg1;
- (void)setSearchTextWithoutSearching:(id)arg1;
- (void)selectFindMethod:(id)arg1;
- (void)backOrForward:(id)arg1;
- (void)backHistory:(id)arg1;
- (void)forwardHistory:(id)arg1;
- (void)backOrForwardMenu:(id)arg1;
- (void)chooseDictionary:(id)arg1;
- (void)changeTextSize:(id)arg1;
- (void)setSelectedDictionaryIndex:(int)arg1;
- (id)selectedDictionary;
- (void)toggleDictionary:(BOOL)arg1;
- (id)contextualMenuForDictionary:(id)arg1 target:(id)arg2 editAction:(SEL)arg3 revertAction:(SEL)arg4;
- (void)startDelayedSearch:(id)arg1 inDictionaries:(id)arg2;
- (void)clearHistories;
- (id)printInfo;
- (void)setPrintInfo:(id)arg1;
- (void)printInfoUpdated;
- (void)doPageLayout;
- (void)didEndPageLayout:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)printContents;
- (BOOL)hasInlineInputArea;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)windowDidBecomeMain:(id)arg1;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabLabelView:(id)arg1 didChangeLabel:(id)arg2;
- (void)tabHeaderView:(id)arg1 didShowHide:(BOOL)arg2 delta:(float)arg3;
- (void)dictionaryController:(id)arg1 didSelectRecord:(id)arg2 reflectSearchField:(BOOL)arg3;
- (void)dictionaryController:(id)arg1 snapCurrentScrollPosition:(float)arg2 forScope:(int)arg3 create:(BOOL)arg4;
- (void)dictionaryController:(id)arg1 cacheRemoteContents:(id)arg2 forDictionary:(id)arg3;
- (void)dictionaryController:(id)arg1 didShowHideIndex:(BOOL)arg2;
- (void)dictionaryController:(id)arg1 suggestUnknownWord:(id)arg2;
- (void)dictionaryControllerDidCancelAsyncFind:(id)arg1;
- (void)dictionaryControllerDidClearPreviousResult:(id)arg1;
- (void)dictionaryControllerIndexSelectionWasChanged:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)runDefaultTestSuite:(id)arg1;
- (void)runPerformanceTest:(id)arg1;
- (BOOL)isInSelfTest;
- (void)setSelfTestFlag:(BOOL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)_setupToolbar;
- (void)_snapback:(id)arg1;
- (void)_searchText:(id)arg1 inDictionaryContoller:(id)arg2 withSelection:(id)arg3;
- (id)_dictionaryControllerForTabViewItem:(id)arg1;
- (void)_setActiveBookController:(id)arg1;
- (void)_changeTextSize:(BOOL)arg1;
- (void)_chooseDictionaryByDictionaryIndex:(int)arg1;
- (void)_reinitializeSearchMenu:(id)arg1;
- (void)_reinitializeGoMenu:(id)arg1;
- (void)_showFrontMatterPage:(id)arg1;
- (void)_reinitializeScopebar:(id)arg1;
- (void)_editDictionaryLabel:(id)arg1;
- (void)_editLabelSheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)closeEditLabelSheet:(id)arg1;
- (void)_revertDictionaryLabel:(id)arg1;
- (void)_updateWindowTitle:(id)arg1;
- (void)_addSnapshot:(id)arg1 checkDuplicate:(BOOL)arg2;
- (void)_setSelectionToHistory:(id)arg1;
- (void)_backOrForwardHistory:(int)arg1;
- (void)_reproduceSnapshot:(id)arg1;
- (void)_removeHistoryOfBook:(id)arg1;
- (void)_updateBackForwardMenuAt:(int)arg1;
- (id)_createMenuFromArray:(id)arg1 startIndex:(int)arg2 forBack:(BOOL)arg3;
- (BOOL)_isEqualWithLastSnapshot:(id)arg1;
- (void)_setFoundCount:(int)arg1 forDictionaryController:(id)arg2;
- (void)_setSearchTextSilently:(id)arg1;
- (void)fieldEditor:(id)arg1 changeCompletion:(id)arg2 fixed:(BOOL)arg3;

@end

