/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSSegmentedCell.h"

@class NSEvent, NSMutableDictionary;

@interface DelayedMenuSegmentedCell : NSSegmentedCell
{
    NSMutableDictionary *_privateMenus;
    NSEvent *_lastEvent;
    struct _NSRect _lastCellRect;
    BOOL _lastMouseUpMode;
    double _lastEventTimeSinceReference;
}

- (id)init;
- (void)dealloc;
- (void)setMenu:(id)arg1 forSegment:(int)arg2;
- (id)menuForSegment:(int)arg1;
- (BOOL)trackMouse:(id)arg1 inRect:(struct _NSRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (BOOL)startTrackingAt:(struct _NSPoint)arg1 inView:(id)arg2;
- (void)_postMouseUpEventAt:(struct _NSPoint)arg1 inView:(id)arg2;

@end

