/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class DSDictionaryObj, NSString;

@interface DictionaryRecord : NSObject
{
    NSString *_keyString;
    NSString *_headword;
    NSString *_yomiWord;
    NSString *_anchor;
    NSString *_compositeTitle;
    NSString *_searchedString;
    DSDictionaryObj *_dictionary;
    unsigned int _foundOrder;
    unsigned long long _uniqueID;
}

+ (id)recordWithKey:(id)arg1 dictionary:(id)arg2 headword:(id)arg3 uniqueID:(unsigned long long)arg4;
- (void)dealloc;
- (id)initWithKey:(id)arg1 dictionary:(id)arg2 headword:(id)arg3 uniqueID:(unsigned long long)arg4 yomiWord:(id)arg5 anchor:(id)arg6 foundOrder:(unsigned long)arg7;
- (id)initWithKey:(id)arg1 dictionary:(id)arg2 headword:(id)arg3 uniqueID:(unsigned long long)arg4;
- (BOOL)isEqualToRecord:(id)arg1;
- (id)keyString;
- (id)headword;
- (id)displayTitle;
- (id)yomiWord;
- (id)dictionary;
- (unsigned long long)uniqueID;
- (unsigned long)foundOrder;
- (id)anchor;
- (void)setAnchor:(id)arg1;
- (void)setSearchedString:(id)arg1;
- (id)normalizeTitle:(id)arg1;

@end

