/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "DSDictionaryProtocol-Protocol.h"

@class NSString;

@interface DSDictionaryObj : NSObject <DSDictionaryProtocol>
{
    unsigned int _indexID;
    BOOL _inUse;
    BOOL _inFocus;
    BOOL _isPrivateDictionary;
    NSString *_customLabelName;
    NSString *_modifiedIdentifer;
}

+ (id)availableDictionaries;
+ (id)dictionaryWithIdentifier:(id)arg1;
+ (id)dictionaryWithPath:(id)arg1;
+ (id)_privateDictionaries;
+ (id)_privateDictionaryWithPath:(id)arg1;
+ (id)registeredDictionaries;
- (void)_addToDictionaryObjCacheWithPath:(id)arg1;
- (void)dealloc;
- (BOOL)usableDictionary;
- (unsigned long)indexID;
- (BOOL)inUse;
- (void)setInUse:(BOOL)arg1;
- (BOOL)inFocus;
- (void)setInFocus:(BOOL)arg1;
- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (BOOL)isLocalDictionary;
- (id)noEntriesFoundString;
- (id)dictionaryPathForPrefs;
- (id)parent;
- (id)children;
- (id)activeChildren;
- (id)postProcessScriptForFrame:(id)arg1 loadFinished:(char *)arg2;
- (id)labelName;
- (void)setLabelName:(id)arg1;
- (id)customLabelName;
- (id)description;
- (void)_setIndexID:(unsigned long)arg1;
- (void)_setPrivateDictionary:(BOOL)arg1;
- (id)initWithPath:(id)arg1;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLString;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;

@end

