/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@interface EmbossedTextFieldCell : NSTextFieldCell
{
}

- (void)setStringValue:(id)arg1;
- (id)stringValue;
- (void)drawInteriorWithFrame:(struct _NSRect)arg1 inView:(id)arg2;
- (unsigned int)_translateMode:(int)arg1;

@end

