/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DSDictionaryObj.h"

@class NSBundle, NSLock, NSString, NSURL;

@interface IDXDictionaryObj : DSDictionaryObj
{
    NSString *_dictionaryPath;
    NSString *_contentsPath;
    NSBundle *_bundle;
    NSURL *_baseURL;
    struct __DCSDictionary *_dictionaryRef;
    struct __IDXIndex *_keywordIndex;
    struct __IDXIndex *_bodyDataIndex;
    struct __IDXIndex *_referenceIDIndex;
    NSURL *_cssFileURL;
    NSURL *_xslFileURL;
    NSURL *_prefsHTMLFileURL;
    NSLock *_lockForIDXCall;
}

+ (id)registeredDictionaries;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLString;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
- (id)_createRecordFromDataPtr:(const char *)arg1 size:(unsigned long)arg2 censoring:(BOOL)arg3 foundOrder:(unsigned long)arg4;
- (void)_setKeywordIndex:(struct __IDXIndex *)arg1;
- (struct __CFString *)_IDXMatchingMethodFromDSMatchingMethod:(unsigned int)arg1;
- (BOOL)_parentalControlWithAdustingMaxRecords:(int *)arg1;
- (id)_reformBodyString:(id)arg1;
- (id)_bundle;
- (struct __DCSDictionary *)_dictionaryRef;
- (void)_activatePrivateFont;

@end

