/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DictionaryRecord.h"

@class NSString;

@interface OnlineDictionaryRecord : DictionaryRecord
{
    NSString *_urlString;
}

- (id)initWithKey:(id)arg1 dictionary:(id)arg2 headword:(id)arg3 uniqueID:(unsigned long long)arg4 urlString:(id)arg5;
- (id)urlString;
- (void)dealloc;

@end

