/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DSDictionaryObj.h"

@class NSBundle, NSDictionary, NSLock, NSMutableArray, NSMutableDictionary, NSString, NSURL, WebView;

@interface OnlineDictionaryObj : DSDictionaryObj
{
    NSString *_dictionaryPath;
    NSString *_contentsPath;
    NSDictionary *_infoPlist;
    NSURL *_baseURL;
    NSBundle *_bundle;
    NSString *_identifier;
    NSString *_displayName;
    NSString *_shortDisplayName;
    NSString *_categoryName;
    NSString *_manufacturerName;
    NSString *_copyright;
    NSString *_commonJavaScriptLibraryPath;
    NSString *_dictionaryJavaScriptPath;
    NSString *_queryHTMLTemplate;
    NSString *_bodyHTMLTemplate;
    NSURL *_prefsHTMLFileURL;
    NSMutableDictionary *_prefs;
    double _minimumIndexLookupInterval;
    double _lastIndexLookupTime;
    WebView *_webView;
    NSMutableArray *_indexList;
    NSLock *_indexListLock;
    int _sessionID;
}

+ (id)registeredDictionaries;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLString;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
- (BOOL)isLocalDictionary;
- (void)setInFocus:(BOOL)arg1;
- (BOOL)_isValid;
- (void)_startIndexLookup:(id)arg1;
- (void)_cancelIndexLookup;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2;

@end

