/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TextAccessibilityObj.h"

@interface WebAccessibilityObj : TextAccessibilityObj
{
    struct __AXTextMarkerRange *_lastTextMarkerRange;
    int _maxLengthInRange;
}

- (void)dealloc;
- (BOOL)_isValidUIElement:(id)arg1;
- (id)textForRequestLength:(int)arg1 resultTextOffset:(int *)arg2 resultMouseOffset:(int *)arg3;
- (struct _NSPoint)lastTextOrigin:(struct _NSRange)arg1;
- (id)lastTextAttributesInRange:(struct _NSRange)arg1;
- (BOOL)pointInSelection:(struct _NSPoint)arg1;
- (struct __AXTextMarker *)_createMarkerOffset:(int)arg1 fromMarker:(struct __AXTextMarker *)arg2 useFarther:(BOOL)arg3 actualOffset:(int *)arg4;
- (struct __AXTextMarkerRange *)_createTrimmedTextRange:(struct _NSRange)arg1;
- (BOOL)_marker:(struct __AXTextMarker *)arg1 inMarkerRange:(struct __AXTextMarkerRange *)arg2;
- (struct _NSPoint)_originForMaker:(struct __AXTextMarker *)arg1 accurateBaseline:(BOOL)arg2 baselineRange:(struct __AXTextMarkerRange *)arg3;
- (int)_lineForMaker:(struct __AXTextMarker *)arg1;
- (struct __AXTextMarkerRange *)_makerRangeForLine:(int)arg1;
- (struct _NSRect)_rectForMakerRange:(struct __AXTextMarkerRange *)arg1;
- (int)_lengthInMakerRange:(struct __AXTextMarkerRange *)arg1;
- (id)_normalizeAXAttributeString:(id)arg1;

@end

