/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMutableArray, NSPort;

@interface WikipediaIndexLookupController : NSObject
{
    BOOL _exit;
    NSMutableArray *_requestQueue;
    NSLock *_requestQueueLock;
    NSMutableArray *_validConnections;
    NSLock *_validConnectionsLock;
    NSPort *_controllerPort;
    NSPort *_threadPort;
}

- (id)requestLookupWith:(id)arg1 forDictionary:(id)arg2;
- (void)cancelConnection:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)handlePortMessage:(id)arg1;
- (void)_controllerThread;
- (BOOL)_checkConnection:(id)arg1 invalidate:(BOOL)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;

@end

