/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSURLConnection.h"

@class NSArray, NSLock, NSMutableData, NSString, WebView;

@interface WikipediaIndexLookupURLConnection : NSURLConnection
{
    id _dictionary;
    WebView *_privateWebView;
    NSString *_HTMLFromWikipedia;
    NSArray *_indexesFromWikipedia;
    NSMutableData *_replyData;
    NSLock *_indexesArrayLock;
    BOOL _initiated;
    BOOL _canceled;
}

- (id)initWithRequest:(id)arg1 forDictionary:(id)arg2;
- (id)indexesFromWikipedia;
- (BOOL)initiated;
- (BOOL)completed;
- (BOOL)canceled;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)cancel;
- (void)dealloc;

@end

