/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DSDictionaryObj.h"

@class NSBundle, NSMutableArray, NSMutableDictionary, NSString, NSURL;

@interface WikipediaDictionaryObj : DSDictionaryObj
{
    NSString *_dictionaryPath;
    NSString *_contentsPath;
    NSURL *_baseURL;
    NSBundle *_bundle;
    NSString *_identifier;
    NSString *_displayName;
    NSString *_shortDisplayName;
    NSString *_categoryName;
    NSString *_manufacturerName;
    NSString *_copyright;
    NSString *_prefsHTMLString;
    NSMutableDictionary *_prefs;
    NSString *_bodyHTMLTemplate;
    NSString *_errorHTMLTemplate;
    NSString *_footerHTMLTemplate;
    NSString *_postProcessScriptTemplate;
    NSString *_disclaimerURLString;
    NSMutableArray *_children;
    NSMutableArray *_activeChildren;
    NSString *_extraLanguageCode;
}

- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (BOOL)supportMatchingMethod:(unsigned int)arg1;
- (id)dictionaryPath;
- (id)contentsBaseURL;
- (id)dictionaryName;
- (id)originalIdentifier;
- (id)displayName;
- (id)shortDisplayName;
- (id)categoryName;
- (id)manufacturerName;
- (id)copyright;
- (id)infoDictionary;
- (id)propertyData:(id)arg1;
- (id)cssFileURL;
- (id)xslFileURL;
- (id)prefsHTMLString;
- (id)prefsHTMLFileURL;
- (id)prefs;
- (void)setPrefs:(id)arg1;
- (id)findKey:(id)arg1 byMethod:(unsigned int)arg2 maxRecord:(int)arg3;
- (id)dataStringForRecord:(id)arg1;
- (id)findByReferenceID:(id)arg1;
- (BOOL)isLocalDictionary;
- (id)noEntriesFoundString;
- (id)parent;
- (id)children;
- (id)activeChildren;
- (id)bodyHTMLTemplate;
- (id)errorHTMLTemplate;
- (id)footerHTMLTemplate;
- (id)postProcessScriptTemplate;
- (id)disclaimerURLString;
- (id)extraLanguageCode;
- (void)_setDefaultLanguage:(id)arg1;

@end

