/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSWindowController.h"

@class DictionaryController, DictionaryFilterView, DictionarySearchFieldEditor, NSDictionary, NSFont, NSMutableArray, NSObjectController, NSPrintInfo, NSProgressIndicator, NSSearchField, NSSegmentedControl, NSString, NSTextField, NSWindow;

@interface BrowserWindowController : NSWindowController
{
    NSSegmentedControl *_backForwardBtn;
    NSSegmentedControl *_textSizeBtn;
    NSWindow *_dictionaryLabelSheet;
    NSTextField *_dictionaryLabelField;
    NSSearchField *_searchField;
    NSProgressIndicator *_searchProgressSpinner;
    DictionaryFilterView *_scopeBar;
    NSObjectController *_dictionaryControllerController;
    long long _windowID;
    DictionaryController *_dictionaryController;
    NSString *_searchText;
    unsigned long long _searchMethod;
    NSMutableArray *_historyRecords;
    long long _historyPosition;
    NSDictionary *_reproducingSnapShot;
    NSMutableArray *_queuedAlertRequests;
    int _progressAnimationLevel;
    double _textSizeMultiplier;
    struct CGRect _imageWindowFrame;
    struct CGRect _imageWindowParentFrame;
    double _indexWidthBeforeFullSearch;
    long long _selectedDictionaryIndex;
    BOOL _disableResumeCache;
    BOOL _changingTabByMyself;
    BOOL _changingSearchTextByMyself;
    BOOL _rewindingHistory;
    BOOL _fullTextSearching;
    BOOL _frontMatterMenuItemEnabled;
    BOOL _resumingCache;
    DictionarySearchFieldEditor *_searchFieldEditor;
    NSMutableArray *_dictionariesWithFlags;
    NSFont *_copyrightFont;
    NSPrintInfo *printInfo;
    BOOL _isInSelfTest;
}

+ (id)activeWindowController;
+ (id)defaultWindowTitle;
+ (void)validateAllMenuEquivalents;
+ (void)_reinitializeSearchMenu;
+ (BOOL)_reinitializeFrontMatterMenu;
- (void)windowDidLoad;
- (void)_setAccessibilityDescription:(id)arg1 forControl:(id)arg2 segment:(long long)arg3;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)windowDidResize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)dealloc;
- (void)showWindow:(id)arg1;
- (void)_showAlertFromDictionary:(id)arg1;
- (void)alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (long long)countBook;
- (id)bookForCurrentTab;
- (void)setBookToCurrentTab:(id)arg1;
- (void)addDictionaryToCurrentTab:(id)arg1;
- (void)setupWithBook:(id)arg1;
- (BOOL)setupWithProperty:(id)arg1 frame:(id)arg2;
- (void)_updateBookController;
- (id)retrieveProperty;
- (BOOL)processedSpecialEvent:(id)arg1;
- (void)showRequestedURL:(id)arg1 label:(id)arg2;
- (void)showRequestedStringLongest:(id)arg1 inDictionary:(id)arg2;
- (BOOL)validateMenuItem:(id)arg1;
- (void)startProgressAnimation;
- (void)stopProgressAnimation:(BOOL)arg1;
- (void)historyAvailableForBack:(char *)arg1 forward:(char *)arg2;
- (void)imageWindowFrame:(struct CGRect *)arg1 onParentFrame:(struct CGRect *)arg2;
- (void)setImageWindowFrame:(struct CGRect)arg1;
- (void)setSearchText:(id)arg1;
- (void)setSearchTextWithoutSearching:(id)arg1;
- (void)selectFindMethod:(id)arg1;
- (void)backOrForward:(id)arg1;
- (void)backHistory:(id)arg1;
- (void)forwardHistory:(id)arg1;
- (void)backOrForwardMenu:(id)arg1;
- (void)chooseDictionary:(id)arg1;
- (void)changeTextSize:(id)arg1;
- (void)showFrontMatterPage:(id)arg1;
- (void)updateScopebar;
- (void)setSelectedDictionaryIndex:(long long)arg1;
- (id)selectedDictionary;
- (void)toggleDictionary:(BOOL)arg1;
- (id)contextualMenuForDictionary:(id)arg1 target:(id)arg2 editAction:(SEL)arg3 revertAction:(SEL)arg4;
- (void)startDelayedSearch:(id)arg1 inDictionaries:(id)arg2;
- (void)clearHistories;
- (id)printInfo;
- (void)setPrintInfo:(id)arg1;
- (void)printInfoUpdated;
- (void)doPageLayout;
- (void)didEndPageLayout:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)printContents;
- (BOOL)hasSearchedText;
- (BOOL)hasInlineInputArea;
- (void)setWindowID:(long long)arg1;
- (long long)windowID;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)windowDidBecomeMain:(id)arg1;
- (void)dictionaryController:(id)arg1 didSelectRecord:(id)arg2 reflectSearchField:(BOOL)arg3;
- (void)dictionaryController:(id)arg1 snapCurrentScrollPosition:(double)arg2 forScope:(long long)arg3 create:(BOOL)arg4;
- (void)dictionaryController:(id)arg1 cacheRemoteContents:(id)arg2 forDictionary:(id)arg3;
- (void)dictionaryController:(id)arg1 saveResumeCache:(BOOL)arg2 forDictionary:(id)arg3;
- (void)dictionaryController:(id)arg1 didShowHideIndex:(BOOL)arg2;
- (void)dictionaryController:(id)arg1 suggestUnknownWord:(id)arg2;
- (void)dictionaryControllerDidCancelAsyncFind:(id)arg1;
- (void)dictionaryControllerDidClearPreviousResult:(id)arg1;
- (void)dictionaryControllerIndexSelectionWasChanged:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)runDefaultTestSuite:(id)arg1;
- (void)runPerformanceTest:(id)arg1;
- (BOOL)isInSelfTest;
- (void)setSelfTestFlag:(BOOL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)_snapback:(id)arg1;
- (void)_searchText:(id)arg1 inDictionaryContoller:(id)arg2 withSelection:(id)arg3;
- (void)_setActiveBookController:(id)arg1;
- (void)_changeTextSize:(BOOL)arg1;
- (void)_chooseDictionaryByDictionaryIndex:(long long)arg1;
- (id)_dictionaryController;
- (void)_editDictionaryLabel:(id)arg1;
- (void)_editLabelSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)closeEditLabelSheet:(id)arg1;
- (void)_revertDictionaryLabel:(id)arg1;
- (void)_updateWindowTitle:(id)arg1;
- (void)_addSnapshot:(id)arg1 checkDuplicate:(BOOL)arg2;
- (void)_setSelectionToHistory:(id)arg1;
- (void)_backOrForwardHistory:(long long)arg1;
- (void)_reproduceSnapshot:(id)arg1;
- (void)_removeHistoryOfBook:(id)arg1;
- (void)_updateBackForwardMenuAt:(long long)arg1;
- (id)_createMenuFromArray:(id)arg1 startIndex:(long long)arg2 forBack:(BOOL)arg3;
- (BOOL)_isEqualWithLastSnapshot:(id)arg1;
- (void)_setTimerForSavingCurrentSearchString:(BOOL)arg1;
- (void)_saveCurrentSearchStringForResume;
- (id)_loadResumeCacheData;
- (id)_resumeCacheURLWithFolderCreation:(BOOL)arg1;
- (void)_setSearchTextSilently:(id)arg1;
- (void)fieldEditor:(id)arg1 changeCompletion:(id)arg2 fixed:(BOOL)arg3;

@end

