/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSTextView.h"

@class DictionaryController, DictionaryRecordRepository, NSMutableArray, NSString, NSWindow;

@interface DictionarySearchFieldEditor : NSTextView
{
    id _completionDelegate;
    NSWindow *_parentWindow;
    DictionaryController *_dictionaryController;
    unsigned long long _findMethod;
    DictionaryRecordRepository *_lastFoundRecords;
    NSString *_lastEnteredText;
    BOOL _searchByExternalTrigger;
    BOOL _changingTextByMyself;
    BOOL _lastTextChangeWasDeletion;
    BOOL _returnPressedBeforeSearch;
    BOOL _transactionFinished;
    BOOL _searchedSimilarWords;
    NSMutableArray *_similarWordsList;
    int _currentTextGenerationID;
    int _lastSearchedTextGenerationID;
    int _lastConsolidatedTransactionID;
    int _lastSimilarWordGenerationID;
    BOOL _foundExactMatch;
    BOOL _textChangedDuringSearch;
}

- (void)dealloc;
- (id)completionsForPartialWordRange:(struct _NSRange)arg1 indexOfSelectedItem:(long long *)arg2;
- (void)insertCompletion:(id)arg1 isFinal:(BOOL)arg2;
- (BOOL)shouldChangeTextInRange:(struct _NSRange)arg1 replacementString:(id)arg2;
- (void)didChangeText;
- (void)doCommandBySelector:(SEL)arg1;
- (void)searchText:(id)arg1;
- (void)delayedSearchText:(id)arg1 inBook:(id)arg2;
- (void)setSearchTextSilently:(id)arg1;
- (void)setCompletionDelegate:(id)arg1;
- (void)setDictionaryController:(id)arg1 inWindow:(id)arg2 withFindMethod:(unsigned long long)arg3;
- (id)lastFoundRecords;
- (id)lastEnteredText;
- (void)setSearchByExternalTrigger:(BOOL)arg1;
- (void)cancelRunningAsyncFind;
- (void)setCurrentFoundRecords:(id)arg1;
- (void)_searchCurrentText;
- (void)_searchCurrentTextInBook:(id)arg1 didEndSelector:(SEL)arg2 target:(id)arg3;
- (void)_startProgressAnimation;
- (void)_searchSimilarWords:(id)arg1;
- (void)_asyncFindDidEndSelector:(id)arg1;
- (void)_asyncSimilarWordFindDidEndSelector:(id)arg1;
- (void)_asyncImmediateFindDidEndSelector:(id)arg1;
- (void)_createCompleteList:(id)arg1;
- (void)_createCompleteListForImmediateFind:(id)arg1;
- (id)_caseInsensitiveMutableArray:(id)arg1;
- (void)_wordSelected:(id)arg1 fixed:(BOOL)arg2;
- (void)_selectWholeText;
- (BOOL)_updateLastEnterdText:(id)arg1;
- (BOOL)_isValidTextChange;
- (void)fieldEditor:(id)arg1 changeCompletion:(id)arg2 fixed:(BOOL)arg3;

@end

